//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIintro.Models.databsae
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public string sdob { get; set; }
        public Nullable<int> sdid { get; set; }
    
        public virtual dept dept { get; set; }
    }
}
